interface PipelineStep {
  label: string;
  detail: string;
}

const STEPS: PipelineStep[] = [
  { label: "Synthetic Source Data", detail: "12 months of actual/budget/forecast P&L + units" },
  { label: "SQLite Ledger", detail: "Single-file, auditable database" },
  { label: "Python Validation & FP&A Calculations", detail: "Variance, KPIs, controls, close dependencies" },
  { label: "Reporting Outputs", detail: "KPI Dashboard, Variance Analysis, Close Checklist — this app and the Excel close pack" },
];

const POINTS = [
  "The results shown in this app and the downloadable Excel workbooks are generated by the same automated pipeline — not two separate sources.",
  "The workflow runs validation checks (reconciliation, data completeness, sign-logic) before producing any reporting output.",
  "All data is fictional / synthetic portfolio data.",
];

function formatGeneratedAt(isoString: string): string {
  const date = new Date(isoString);
  if (Number.isNaN(date.getTime())) return isoString;
  // Intl.DateTimeFormat disallows combining dateStyle/timeStyle with a
  // component option like timeZoneName, so this spells out the
  // components individually rather than using the dateStyle shorthand.
  return new Intl.DateTimeFormat("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit",
    timeZone: "UTC",
    timeZoneName: "short",
  }).format(date);
}

export function HowItWorks({ generatedAt }: { generatedAt: string }) {
  return (
    <div className="p-5">
      <ol className="flex flex-col gap-2 lg:flex-row lg:items-stretch lg:gap-2">
        {STEPS.map((step, index) => (
          <li key={step.label} className="flex flex-1 items-center gap-2">
            <div className="flex-1 rounded-lg border border-[var(--color-border)] bg-[var(--color-surface-muted)] px-4 py-3">
              <p className="flex items-center gap-2 text-sm font-semibold text-[var(--color-navy)]">
                <span
                  className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-[var(--color-navy)] text-[11px] font-bold text-white"
                  aria-hidden="true"
                >
                  {index + 1}
                </span>
                {step.label}
              </p>
              <p className="mt-1 pl-7 text-xs text-[var(--color-ink-secondary)]">{step.detail}</p>
            </div>
            {index < STEPS.length - 1 ? (
              <span
                className="hidden shrink-0 text-lg text-[var(--color-ink-muted)] lg:inline"
                aria-hidden="true"
              >
                →
              </span>
            ) : null}
          </li>
        ))}
      </ol>

      <ul className="mt-5 flex flex-col gap-2">
        {POINTS.map((point) => (
          <li key={point} className="flex gap-2 text-sm text-[var(--color-ink-secondary)]">
            <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-[var(--color-accent)]" aria-hidden="true" />
            {point}
          </li>
        ))}
      </ul>

      <p className="mt-4 text-xs text-[var(--color-ink-muted)]">
        Last generated: <span className="font-medium text-[var(--color-ink-secondary)]">{formatGeneratedAt(generatedAt)}</span>
      </p>
    </div>
  );
}
